name: Test-Suite

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
    name: Test-Suite for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Start Test Infrastructure
        run: |
          bash ./tests/start_infra.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pip
        run: |
          python -m pip install --upgrade pip wheel

      - name: Install dependencies
        run: |
          python -m pip install pytest pytest-cov
          python -m pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

      - name: Teardown Test Infrastructure
        if: always()
        run: |
          bash ./tests/start_infra.sh
        shell: bash
